default_context:
  project_name: 'Open-Pantheon'
  project_slug: 'open-pantheon'
  domain_main: 'open-pantheon.org'
  domain_staging: 'stag.open-pantheon.org'
  docker_swarm_stack_name_main: 'open-pantheon-com'
  docker_swarm_stack_name_staging: 'stag-open-pantheon-com'
  secret_key: '18dad840c9f48d1a2209823b6f140eab3bd2f51a4b782c8a4d2d9a1b07df6638'
  first_superuser: 'admin@open-pantheon.org'
  first_superuser_password: 'c3f358c26f4eae6c5c07f847d8e78de7854d87edbd12d2c9382ce29c1debee1d'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.open-pantheon.org", "https://stag.open-pantheon.org", "https://open-pantheon.org", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@open-pantheon.org'
  postgres_password: '6f649af26564659f4ce95fc5615f111e9a787230593d1ea75dd3a7fb91b4168f'
  pgadmin_default_user: 'admin@open-pantheon.org'
  pgadmin_default_user_password: 'c3f358c26f4eae6c5c07f847d8e78de7854d87edbd12d2c9382ce29c1debee1d'
  traefik_constraint_tag: 'open-pantheon.org'
  traefik_constraint_tag_staging: 'stag.open-pantheon.org'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:c3f358c26f4eae6c5c07f847d8e78de7854d87edbd12d2c9382ce29c1debee1d'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
