"""Comments fix

Revision ID: 749d2b6f5d70
Revises: ad25823c6600
Create Date: 2021-08-24 01:20:29.524279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '749d2b6f5d70'
down_revision = 'ad25823c6600'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###