"""Comments fix

Revision ID: 97b52bb5c299
Revises: de19eb5ca4fc
Create Date: 2021-08-24 13:00:53.094145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97b52bb5c299'
down_revision = 'de19eb5ca4fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###