"""Refractor personality

Revision ID: baa74eddc40f
Revises: 9f1fdf55725b
Create Date: 2021-08-22 00:36:48.315772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baa74eddc40f'
down_revision = '9f1fdf55725b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personality', sa.Column('wikipedia_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_personality_wikipedia_id'), 'personality', ['wikipedia_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_personality_wikipedia_id'), table_name='personality')
    op.drop_column('personality', 'wikipedia_id')
    # ### end Alembic commands ###