"""Comments fix

Revision ID: de19eb5ca4fc
Revises: 749d2b6f5d70
Create Date: 2021-08-24 01:21:02.983059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de19eb5ca4fc'
down_revision = '749d2b6f5d70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###