name: ci

on:
  push:
    branches:
      - develop
      - pipeline
    tags:
      - "v*.*.*"

jobs:
  docker:
    needs:
      - email-template
      - format-frontend
      - format-backend
      - license
    runs-on: k8s-runner
    strategy:
      matrix:
        app: [ "frontend", "backend" ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
      - name: Get version tag
        id: version_tag
        run: |
          if [[ ! "$GITHUB_REF" =~ refs/tags ]]; then
            echo "::set-output name=value::latest"
          else
            echo "::set-output name=value::${GITHUB_REF#refs/tags/}"
          fi
      - name: Docker Login Dev
        if: startsWith(github.ref, 'refs/tags/') != true
        uses: docker/login-action@v1
        with:
          registry: cridevlab.azurecr.io
          username: ${{ secrets.DOCKER_DEV_USERNAME }}
          password: ${{ secrets.DOCKER_DEV_PASSWORD }}
      - name: Build and push Dev
        if: startsWith(github.ref, 'refs/tags/') != true
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.app }}
          push: true
          tags: cridevlab.azurecr.io/open-pantheon-${{ matrix.app }}:${{ steps.version_tag.outputs.value }}
      - name: Docker Login Staging
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/login-action@v1
        with:
          registry: cristaglab.azurecr.io
          username: ${{ secrets.DOCKER_STAG_USERNAME }}
          password: ${{ secrets.DOCKER_STAG_PASSWORD }}
      - name: Build and push Staging
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.app }}
          push: true
          tags: cristaglab.azurecr.io/open-pantheon-${{ matrix.app }}:${{ steps.version_tag.outputs.value }}

#example of using kubectl
#      - uses: azure/setup-kubectl@v1
#      - name: kubectl
#        run: kubectl get pods
