# OpenPantheon: the pantheon for Education
# Copyright (C) 2021 CRI
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
name: Code formatting & linting
on:
  push:
    branches:
      - develop
      - staging
      - main
  pull_request:
    branches:
      - develop
jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: yarn
          cache-dependency-path: frontend/yarn.lock
      - name: Install the dependencies
        working-directory: frontend
        run: yarn install --non-interactive --frozen-lockfile
      - name: Check the code formatting
        working-directory: frontend
        run: yarn format:check
      - name: Lint
        working-directory: frontend
        run: yarn lint

  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: pip
          restore-keys: |
            pip
      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry
          key: poetry-${{ hashFiles('backend/app/poetry.lock') }}
          restore-keys: |
            poetry-
      - name: Install dependencies
        working-directory: backend/app
        run: poetry install --no-root
      - name: Check the code formatting
        working-directory: backend/app
        run: |
          # Activate poetry's virtualenv
          source `poetry env info --path`/bin/activate
          # Run formatting tools
          ./scripts/format.sh
          # Check that there are no changes
          git diff --exit-code
      - name: Lint
        working-directory: backend/app
        run: |
          # Activate poetry's virtualenv
          source `poetry env info --path`/bin/activate
          # Run the linter tools
          ./scripts/lint.sh
