name: Unit tests
on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - main
jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: yarn
          cache-dependency-path: frontend/yarn.lock
      - name: Install the dependencies
        working-directory: frontend
        run: yarn install --non-interactive --frozen-lockfile
      - name: Run unit tests
        working-directory: frontend
        run: yarn test:unit
